language: ruby
rvm:
  - 2.3.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database one_maths_test' -U postgres
