--- !ruby/object:ActionController::Parameters
parameters: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  reward_mtp: '0.3'
  lower_level: '0.65'
  upper_level: '0.65'
  lower_min: '0.25'
  upper_min: '0.25'
  hints: &1
  - 'Give all solutions correct to 2 d.p, exact integer solutions are also allowed.
    (e.g: 2 or 0.61)'
  - Give integer solution, or solution correct to 2 d.p.
  - Give integer solutions.
  - Give exact integer or fractional solutions (e.g. 3, -2/5).
  - Give the boundary values of x as exact integers or fractions (e.g. x>5, x<=-2/3).
  - New hint has been added via the settings controller.
permitted: true
converted_arrays: !ruby/object:Set
  hash:
    *1: true
