# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$(document).ready ->
  acc = document.getElementsByClassName('accordion')
  i = undefined
  i = 0
  while i < acc.length

    acc[i].onclick = ->
      @classList.toggle 'active'
      @nextElementSibling.classList.toggle 'show'
      return

    i++

# ---
# generated by js2coffee 2.2.0
